<a href="https://colab.research.google.com/github/evansemet/Jane-Street-Solutions/blob/main/2014_07_Chain_Reaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Even though the general logic of this solution works, it will never be able to finish finding the longest possible sequence. Some more constraints/optimizations for the solver need to be given. When I have time, I will come back to this and optimize it.

In [2]:
!pip install z3-Solver
import numpy as np
import time
from z3 import *

In [3]:
# solve function using Z3
def solve(length):
    start = time.time()

    # Setup
    s = Solver()
    X = [Int('x%s' % i) for i in range(length)]

    # makes sure each number is from 1 to 100 and no duplicates
    s += [And(val >= 1, val <= 100) for val in X]
    s += [Distinct(X)]

    # divisibility constraints
    s += [Or(X[i] % X[i + 1] == 0, X[i + 1] % X[i] == 0) for i in range(length - 1)]

    if s.check() == sat:
        m = s.model()
        evalu = np.vectorize(lambda x: m.evaluate(x).as_long())
        r = evalu(X)
        print(r)
        print(f"Solved in {time.time() - start} seconds.")
        return True
    else:
        print(f"Failed in {time.time() - start} seconds.")
        return False

In [4]:
# loops through all lengths until it can't find a longer sequence
for tryLength in range(1, 100):
    print(f"Trying length {tryLength}...")
    if not solve(tryLength):
        break
    print("-------------------------")

Trying length 1...
[65]
Solved in 0.041590213775634766 seconds.
-------------------------
Trying length 2...
[8 4]
Solved in 0.3918726444244385 seconds.
-------------------------
Trying length 3...
[35  5  1]
Solved in 0.10031580924987793 seconds.
-------------------------
Trying length 4...
[ 1 99 33 66]
Solved in 0.36628055572509766 seconds.
-------------------------
Trying length 5...
[99  3 93  1 84]
Solved in 0.27239513397216797 seconds.
-------------------------
Trying length 6...
[28  4 32  2  1 11]
Solved in 0.44192075729370117 seconds.
-------------------------
Trying length 7...
Failed in 48.41996359825134 seconds.
